### ISSUE TITLE
DATECS DPP-250

### ISSUE THREAD

**Issue by apocalipse9** [kechankrisna/pos_printer_manager#1]
Hello, i'm trying to use your library. For a china generic print model it's working, but with Datecs DPP 250 it's not working.
I already try to set CapabilityProfile and setGlobalCodeTable, change the printing content but not's working.

The printer seens receivind data, but not happens.

Could you help?

**Comment by kechankrisna** [comment]
You can read more document about Chinese character at this plugin: https://pub.dev/packages/esc_pos_utils
