### ISSUE TITLE
Reduced quality on Android printing over wifi

### ISSUE THREAD

**Issue by Lyazz** [kechankrisna/pos_printer_manager#11]
Hello there, I have been using this library for a while on Windows (over Wi-Fi) without any problem, since I used the same code on Android to print also over Wi-Fi on the same printer, I noticed that the printing quality was really bad with almost unreadable text. can you please help.

**Comment by kechankrisna** [comment]
> Hello there, I have been using this library for a while on Windows (over Wi-Fi) without any problem, since I used the same code on Android to print also over Wi-Fi on the same printer, I noticed that the printing quality was really bad with almost unreadable text. can you please help.

Can you attach the photo of both printed receipt here?

**Comment by kechankrisna** [comment]
none detail
