### ISSUE TITLE
no use

### ISSUE THREAD

**Issue by selvam920** [kechankrisna/pos_printer_manager#12]
without migrating to null safety there is no use this plugin.

unable to configure latest flutter version

**Comment by kechankrisna** [comment]
> without migrating to null safety there is no use this plugin.
> 
> unable to configure latest flutter version



> without migrating to null safety there is no use this plugin.
> 
> unable to configure latest flutter version

I will merge it soon to null safety. thank for notify me.

**Comment by selvam920** [comment]
once published to pub let us know, we are waiting to try this.

**Comment by selvam920** [comment]
pls merge null safety for this package as well

**Comment by kechankrisna** [comment]
null safety was merged

**Comment by selvam920** [comment]
is this only for android? bcoz in pub.dev showing only android

**Comment by kechankrisna** [comment]
I will migrate window later. Currently, only support android. Anyway, you can use [pos_printer_man](https://pub.dev/packages/pos_printer_manager) for windows support

**Comment by selvam920** [comment]
ok sure will use it android now, pls update to other platform also

**Comment by selvam920** [comment]
im getting below error in android.
_CastError (type 'Future<dynamic>' is not a subtype of type 'FutureOr<List<dynamic>>' in type cast)

![image](https://user-images.githubusercontent.com/20491308/146478886-f5a89fa0-28dd-4f57-a68d-d0717b63a823.png)
