### ISSUE TITLE
Can use for Label printers?

### ISSUE THREAD

**Issue by vukhacbiet** [kechankrisna/pos_printer_manager#13]
I'm having trouble connecting and printing from a label printer with ** esc_pos_printer** package (specifically the XPrinter 350BM).

Label paper is fixed width and height (ex: 40x25mm, 50x30mm,...)

![image](https://user-images.githubusercontent.com/43400653/146789401-9fe5ae44-00de-4161-8963-54baed948df0.png)

I tried to connect printer and set pagesize at 80mm, connect success but nothing is printed.

Can you tell me that this package can print with a label printer?

**Comment by kechankrisna** [comment]
Sorry i have never tried this label print with xPrinter. this package is write data directly to socket or usb, and it is now support only 58 mm and 80 mm. For you label paper, it might need to convert this into pdf with correct size with and height, then just use printing usb, it will work.
