### ISSUE TITLE
Error [pos_printer_manager] [ERROR] can not open on windows

### ISSUE THREAD

**Issue by sergiotucano** [kechankrisna/pos_printer_manager#16]
Hi! 

When I try to connect the manager I recieve this error:
"[pos_printer_manager] [ERROR] can not open"

I be creating the print manually :

```
List<USBPrinter> _printers = [];
USBPrinterManager _manager;

_printers.add(USBPrinter(
    id: null,
    name: 'test',
    address: '\\192.168.1.8\epson',
    connected: false,
    type: 0,
    connectionType: ConnectionType.usb)
);

var manager = USBPrinterManager(_printers[0], paperSize, profile);
await manager.connect(); //line with error 
```

Where is my error?

OPS ! If I try to connect and printing with USBPrinterManager.discover() listed printers all is ok.

I'm using the plugin version 0.0.5.

thanks !

**Comment by kechankrisna** [comment]
Can you confirm if address is correct, please use the address that get from discover method, while it consists the correct name which will be used as address to print.

**Comment by sergiotucano** [comment]
So... I'll be able to print if the name is exactly the same that in Printers screen of the windows?

**Comment by sergiotucano** [comment]
I connect with success and print passing the port in the name property.
Thanks ! 

But, now I've a issue with network printing. 

Two Computers in the same network... In one computer the discover() return exception 5023, what exception is this?

In other, the discover() get the address of my printer and all work's ok.

**Comment by kechankrisna** [comment]
Please provide me the screenshot of the error, those might be happen when you try to discover and print in the same time. In the example, I didn't include disconnect port after printed, This will cause other devices, failed to test print.
