### ISSUE TITLE
will we have usb support in Desktop?, I need that functionality

### ISSUE THREAD

**Issue by MarcoGolin** [kechankrisna/pos_printer_manager#2]

**Comment by kechankrisna** [comment]
It will be added later, as I have to finished some projects first before continue to continue to release some more features.

**Comment by MarcoGolin** [comment]
anxiously waiting

**Comment by kechankrisna** [comment]
> anxiously waiting

I have tried printing direct with printer, by using window print, But the receipt image quality getting 30% lower than network printer. I will update usb as soon as I found the best solution.

**Comment by kechankrisna** [comment]
usb support now for windows and android

**Comment by MarcoGolin** [comment]
> usb support now for windows and android

its working perfectly, thanks!,

**Comment by Lyazz** [comment]
> > anxiously waiting
> 
> I have tried printing direct with printer, by using window print, But the receipt image quality getting 30% lower than network printer. I will update usb as soon as I found the best solution.

---> 
Even when the usb update I always got 30% quality

**Comment by kechankrisna** [comment]
> > > anxiously waiting
> > 
> > 
> > I have tried printing direct with printer, by using window print, But the receipt image quality getting 30% lower than network printer. I will update usb as soon as I found the best solution.
> 
> --->
> Even when the usb update I always got 30% quality

Can you provide your snippet to make sure the image conversion doesn't reduce quality of image bit
