### ISSUE TITLE
Null Safety support

### ISSUE THREAD

**Issue by renanzdm** [kechankrisna/pos_printer_manager#3]
hello congratulations on the package, but I was wondering if you have a chance of migrating to null safety ?. I'm willing to help

**Comment by kechankrisna** [comment]
It will be added later

**Comment by Bavon101** [comment]
> hello congratulations on the package, but I was wondering if you have a chance of migrating to null safety ?. I'm willing to help

I would also want to help if required to, I recently migrated my code to null safety and now I'm forced to remove the printing functionality.

**Comment by kechankrisna** [comment]
Sorry for late update, because I just need to release one app in urgent. After that I will need some helps for null safety support.

**Comment by sonphamtrung17** [comment]
Any plans for this ? @kechankrisna

**Comment by renanzdm** [comment]
> Any plans for this ? @kechankrisna

https://pub.dev/packages/flutter_bluetooth_printer

**Comment by kechankrisna** [comment]
> > Any plans for this ? @kechankrisna
> 
> https://pub.dev/packages/flutter_bluetooth_printer

sorry for being late to merge it into null safety.

**Comment by kechankrisna** [comment]
null safety was merged
