### ISSUE TITLE
Windows error

### ISSUE THREAD

**Issue by fuadrivai** [kechankrisna/pos_printer_manager#5]
Hi, I try to run in windows and i got this error, can you help how to solve this?

![image](https://user-images.githubusercontent.com/50818216/130382174-899af20e-8358-476c-960c-321d16b560d0.png)

**Comment by kechankrisna** [comment]
> Hi, I try to run in windows and i got this error, can you help how to solve this?
> 
> ![image](https://user-images.githubusercontent.com/50818216/130382174-899af20e-8358-476c-960c-321d16b560d0.png)

Can you run command:
flutter clean && flutter pub get 
Then see what will happen.

**Comment by fuadrivai** [comment]
Still nothing, i know this issue comes from printing plugin.
thanks for response.

**Comment by A1000carZ** [comment]
Same issue.

**Comment by A1000carZ** [comment]
![image](https://user-images.githubusercontent.com/52839764/130558551-9a442cf8-ed8f-4c5a-9614-b95c41e4474c.png)
