### ISSUE TITLE
Can we print QR codes with this library ?

### ISSUE THREAD

**Issue by Lyazz** [kechankrisna/pos_printer_manager#6]
Before everything I have to thank you for this awesome lib.
   Can we print QR codes with this library please?

**Comment by kechankrisna** [comment]
> Before everything I have to thank you for this awesome lib.
> Can we print QR codes with this library please?

Yes you can print text, qrcode, or image

**Comment by Lyazz** [comment]
Yes, i tried it successfully using a local api, thanks.
