### ISSUE TITLE
Question on printing the text.

### ISSUE THREAD

**Issue by yawtong1996** [kechankrisna/pos_printer_manager#7]
Hi, is it possible to print the text using PosStyle from esc_pos_utils instead of converting from html? Thank you in advance.

**Comment by kechankrisna** [comment]
> Hi, is it possible to print the text using PosStyle from esc_pos_utils instead of converting from html? Thank you in advance.

Yes it is absolutely possible.

**Comment by bxxasn** [comment]
Very, very concerned

**Comment by kechankrisna** [comment]
> Very, very concerned

What you concern about?
