### ISSUE TITLE
only one blue device is found

### ISSUE THREAD

**Issue by bxxasn** [kechankrisna/pos_printer_manager#8]
1. Only one Bluetooth device can be found, although there are several Bluetooth devices nearby
2. Table printing is not supported. Now only HTML text is supported（like esc_pos_utils  https://pub.dev/packages/esc_pos_utils）

**Comment by bxxasn** [comment]
Look at the Android code, which calls getbondeddevices
This is a problem. This will only return the connected devices, not all the attached devices.
It is recommended to add a method to return all devices

**Comment by bxxasn** [comment]
need to add a scan timeout, otherwise it will continue to loop

**Comment by kechankrisna** [comment]
I am considering this
